services:
    warezgibzzz_custom_map.form.type.custom_map:
        class: Warezgibzzz\CustomMapFormTypeBundle\Form\Type\CustomMapType
        arguments:
            - "%warezgibzzz_custom_map.size%"
            - "%warezgibzzz_custom_map.default%"
            - "%warezgibzzz_custom_map.parameters%"
        tags:
            - { name: form.type, alias: custom_map }
